Repository nlenno1/team-5-may-2022, pull requests merged in 2022-05, with the labels that each got.

#10 Create pull_request_template.md
  docs/pull_request_template.md
Labels: documentation

#16 Add home app and templates
  home/__init__.py
  home/admin.py
  home/apps.py
  home/migrations/__init__.py
  home/models.py
  home/templates/home/index.html
  home/tests.py
  home/urls.py
  home/views.py
  reachout/settings.py
  reachout/urls.py
  templates/base.html
Labels: enhancement

#21 fix: correct error in home urls.py to allow correct rendering of pages
  home/urls.py
Labels: bug

#22 feat: Add environ to improve DB security
  reachout/settings.py
  requirements.txt
Labels: enhancement

#26 Add color scheme image to Readme.md
  README.md
Labels: documentation

#37 Adding Gunicorn server to run Django in heroku
  requirements.txt
Labels: bug

#42 31 create models views and forms for connection request functionality
  .vscode/settings.json
  connectionrequest/admin.py
  connectionrequest/forms.py
  connectionrequest/migrations/0001_initial.py
  connectionrequest/models.py
  connectionrequest/templates/connectionrequest/connection-email/connection-email-body.txt
  connectionrequest/templates/connectionrequest/connection-email/connection-email-subject.txt
  connectionrequest/templates/connectionrequest/respond-to-connection-request.html
  connectionrequest/templates/connectionrequest/response-email/response-email-body.txt
  connectionrequest/templates/connectionrequest/response-email/response-email-subject.txt
  connectionrequest/templates/connectionrequest/search-for-request.html
  connectionrequest/templates/connectionrequest/send-request.html
  connectionrequest/urls.py
  connectionrequest/utils.py
  connectionrequest/views.py
  home/templates/home/index.html
  reachout/settings.py
  reachout/urls.py
  static/css/base.css
Labels: enhancement

#48 Update Allauth Forms
  connectionrequest/views.py
  static/css/allauth.css
  templates/allauth/account/account_inactive.html
  templates/allauth/account/base.html
  templates/allauth/account/email.html
  templates/allauth/account/email_confirm.html
  templates/allauth/account/login.html
  templates/allauth/account/logout.html
  templates/allauth/account/password_change.html
  templates/allauth/account/password_reset.html
  templates/allauth/account/password_reset_done.html
  templates/allauth/account/password_reset_from_key.html
  templates/allauth/account/password_reset_from_key_done.html
  templates/allauth/account/password_set.html
  templates/allauth/account/signup.html
  templates/allauth/account/signup_closed.html
  templates/allauth/account/verification_sent.html
  templates/allauth/account/verified_email_required.html
Labels: enhancement

#50 Add duplicate pull request check and add user email from allauth
  connectionrequest/views.py
  reachout/settings.py
Labels: documentation

#59 add relation field to model, forms and update connection request email
  connectionrequest/forms.py
  connectionrequest/migrations/0002_auto_20220521_2243.py
  connectionrequest/models.py
  connectionrequest/templates/connectionrequest/connection-email/connection-email-body.txt
  connectionrequest/templates/connectionrequest/connection-email/connection-email-subject.txt
  connectionrequest/templates/connectionrequest/response-email/response-email-body.txt
  connectionrequest/utils.py
  connectionrequest/views.py
Labels: documentation

#68 Enhancement: resolves #27 About Us page by fixing team members cards …
  home/templates/home/about-us.html
  media/abhisek-joshi.jpg
  media/baiju-abraham.jpg
  media/img-placeholder.jpg
  media/joy-zadan.jpg
  media/nick-lennon.jpg
  media/sam-dainton.jpg
  media/sam-dainton.webp
  static/css/base.css
  static/img/sam-dainton.webp
  templates/includes/navbar.html
Labels: enhancement

#70 Fix migrations and update send connection request email options
  connectionrequest/migrations/0001_initial.py
  connectionrequest/migrations/0002_auto_20220521_2243.py
  connectionrequest/migrations/0003_alter_connectionrequest_relation.py
  connectionrequest/migrations/0003_auto_20220522_1415.py
  connectionrequest/models.py
  connectionrequest/templates/connectionrequest/connection-email/connection-email-body.txt
Labels: enhancement

#85 fix: fix allauth templating error and add conditional to set developm…
  reachout/settings.py
Labels: bug
